{
  imports = [
    ./hardware-configuration.nix
    ./hardware.nix
    ./bootloader.nix
    ./users.nix
    ./virt.nix
    ./security.nix
    ./services.nix
    ./autologin.nix
    ./pipewire.nix
    ./quiet-boot.nix
    ./network.nix
    ./stylix.nix
    ./fonts.nix
    ./environment.nix
    ./thinkpad.nix
    ./xremap.nix
  ];
}
